#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p \
	/config/geoip2db

# remove lua bits from nginx.conf if not done before
if ! grep -q '#Removed lua' nginx.conf; then 
  echo "Removing lua specific info from nginx.conf"
  sed -i 's|\tlua_load_resty_core off;|\t#Removed lua. Do not remove this comment|g' nginx.conf
fi

# create GeoIP2 folder symlink
[[ -d /var/lib/libmaxminddb ]] && [[ ! -L /var/lib/libmaxminddb ]] && \
  rm -rf /var/lib/libmaxminddb
[[ ! -d /var/lib/libmaxminddb ]] && \
  ln -s /config/geoip2db /var/lib/libmaxminddb
# check GeoIP2 database
if [ -f /var/lib/libmaxminddb/GeoLite2-City.mmdb ]; then
  echo "GeoIP2 database found"
else
  echo "Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb"
fi