#!/usr/bin/with-contenv bash

if [[ -f /config/nginx/geoip2.conf ]]; then
    echo "/config/nginx/geoip2.conf exists.
        Please migrate to https://github.com/linuxserver/docker-mods/tree/swag-maxmind"
fi
